/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.2).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Pricing;
import io.swagger.model.PricingCriteria;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-03-06T15:59:07.679Z")

@Api(value = "pricing", description = "the pricing API")
public interface PricingApi {

    @ApiOperation(value = "Updates a Pricing form data", nickname = "updatePricingIdWithForm", notes = "", response = Pricing.class, tags={ "pricing", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successfull operation", response = Pricing.class),
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/pricing",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Pricing> updatePricingIdWithForm(@ApiParam(value = "ID of PricingId that needs to be updated" ,required=true )  @Valid @RequestBody PricingCriteria body);

}
